### ISSUE TITLE
Resume Display on Profile Page

### ISSUE THREAD

**Issue by nimesh7283** [biunce/YDS-Resume#1]
This error ocurrred when I clicked on the resume view option. I have attached the error file for your reference.
![resumedisplay](https://cloud.githubusercontent.com/assets/12139726/7352023/a0980a7c-ed26-11e4-9983-001120668c04.jpg)
![profilepage](https://cloud.githubusercontent.com/assets/12139726/7352088/17470b3c-ed27-11e4-82b2-5882188281f4.JPG)

**Comment by biunce** [comment]
This is not an error page but this page is yet to be designed. I would get a designer to design this page

**Comment by nimesh7283** [comment]
Please let me know once the page is designed. We need to do it as soon as possible.

**Comment by biunce** [comment]
shortly. but on Priority

**Comment by biunce** [comment]
Done please verify it

**Comment by nimesh7283** [comment]
![Uploading Resume view error.jpg…]()

**Comment by nimesh7283** [comment]
I am still getting error for viewing resume .
![Uploading Resume view error.jpg…]()

**Comment by nimesh7283** [comment]
![Uploading Resume view error.jpg…]()

**Comment by nimesh7283** [comment]
I have emailed you the error file. Please check

**Comment by biunce** [comment]
Its Done

**Comment by biunce** [comment]
Done
